config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :review_comments
    resources :book_ratings
  end

  get "users/profile"
  devise_for :users

  root "users#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :review_comments, dependent: :destroy
  has_many :book_ratings, dependent: :destroy

  has_attached_file :book_image,
    styles: { medium: "300x300#", thumb: "100x100>" },
    default_url: ":style/book.jpeg"

  validates_attachment_content_type :book_image, content_type: %r{\Aimage\/.*\Z}

  validates :title, :review, presence: true

  def rating
    return unless book_ratings.any?

    book_ratings.sum(:rating_value) / book_ratings.count.to_f
  end
end

app/models/book_rating.rb
class BookRating < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :user_id, uniqueness: { scope: :book_id }

  validates :rating_value, inclusion: { in: 0..10 }, presence: true
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  validates :body, presence: true

  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :review_comments, dependent: :destroy
  has_many :book_ratings, dependent: :destroy

  has_attached_file :avatar,
    styles: { medium: "300x300>", thumb: "100x100#" },
    default_url: ":style/missing.jpeg"

  validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\Z}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: %i[email avatar password])
    devise_parameter_sanitizer.permit(:account_update,
      keys: %i[email avatar password current_password])
  end

  private

    def user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/book_ratings_controller.rb
class BookRatingsController < ApplicationController
  expose :book_rating
  expose :book

  responders :location
  respond_to :html

  def create
    book_rating.book = book
    book_rating.user = current_user
    authorize book_rating
    book_rating.save
    respond_with(book_rating, location: book_rating.book)
  end

  def update
    authorize book_rating
    book_rating.update book_rating_params
    respond_with(book_rating, location: book_rating.book)
  end

  def destroy
    authorize book_rating
    book_rating.destroy
    respond_with(book_rating, location: book_rating.book)
  end

  private

  def book_rating_params
    params.require(:book_rating).permit(
      :rating_value,
      :book_id
    )
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  responders :location
  respond_to :html

  expose :book
  expose :books, -> { Book.all }
  expose :book_rating, -> { fetch_book_rating }

  def create
    book.user = current_user
    authorize book
    book.save
    respond_with (book)
  end

  def update
    authorize book
    book.user = current_user
    book.update book_params
    respond_with(book)
  end

  def destroy
    authorize book
    book.destroy
    respond_with(book, location: books_path)
  end

  private

  def fetch_book_rating
    current_user.book_ratings.find_by(book_id: book.id)
  end

  def book_params
    params.require(:book).permit(
      :title,
      :review,
      :book_image,
      :created_at
    )
  end
end

app/controllers/review_comments_controller.rb
class ReviewCommentsController < ApplicationController
  expose :review_comments
  expose :review_comment
  expose :book

  responders :location
  respond_to :html

  def create
    review_comment = book.review_comments.create(review_comment_params)
    review_comment.user = current_user
    authorize review_comment
    review_comment.save
    respond_with(review_comment.book, location: book)
  end

  def update
    authorize review_comment
    review_comment.update(review_comment_params)
    respond_with(review_comment, location: review_comment.book)
  end

  def destroy
    authorize review_comment
    review_comment = book.review_comments.find(params[:id])
    review_comment.destroy
    respond_with(review_comment.book, location: book)
  end

  private

  def review_comment_params
    params.require(:review_comment).permit(
      :title,
      :body,
      :book_id
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  expose :user, -> { current_user }

  def update_password
    if user.update_with_password(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to user,
        notice: "User\"s information was successfully updated."
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(
      :password,
      :password_confirmation,
      :first_name,
      :last_name,
      :email,
      :id,
      :avatar
    )
  end
end

app/views/book_ratings/_book_rating.html.slim
- book_ratings.each do |book_rating|
  tr
    td = book_rating.rating_value
    td = book_rating.book
    td = link_to 'Show', book_book_rating
    td = link_to 'Edit', edit_book_book_rating_path(book_rating)
    td = link_to 'Destroy', book_rating, data: { confirm: 'Are you sure?' }, method: :delete

app/views/book_ratings/_form.html.slim
= form_for [:book, book_rating] do |f|
  - if book_rating.errors.any?
    #error_explanation
      h2 = "#{pluralize(book_rating.errors.count, "error")} prohibited this book_rating from being saved:"
      ul
        - book_rating.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :rating_value
    = f.number_field :rating_value
  .actions = f.submit

app/views/book_ratings/edit.html.slim
h1 Editing book_rating

== render 'form'

=< link_to 'Back', @book

app/views/book_ratings/index.html.slim
h1 Listing book_ratings

table
  thead
    tr
      th Rating value
      th Book
      th
      th
      th

  tbody
    = render 'book_rating'

br

/ = link_to 'New Book rating', new_book_rating_path

app/views/book_ratings/new.html.slim
h1 New book_rating

== render 'form'

app/views/book_ratings/show.html.slim
p
  strong Rating value:
  = book_rating.rating_value
p
  strong Book:
  = book_rating.book.id
- if policy(book).update?
  => link_to 'Edit', edit_book_book_rating_path(book_rating)
'|
- if policy(book).destroy?
  =< link_to 'Back', book_book_rating_path

app/views/books/_book_rating.html.slim
= form_for [book, book.book_ratings.new] do |f|
  = f.label :rating_value
  = f.number_field :rating_value

  = f.submit

app/views/books/_books.html.slim
- books.each do |b|
  .book data-book-id="#{b.id}"
    .card style=("width: 18rem;")
      .card-img-top = image_tag b.book_image.url(:medium)
      .card-body
        h3.card-title
          dl
            dd = b.title
        p.card-text
          dl
            dt Review:
            dd = b.review
        p.card-text
          dl
            dt User:
            dd = b.user.email
        p.card-text
          dl
            dt Overrall rating:
            dd
              = b.rating.presence || "No rating yet"
        .btn-toolbar
        .btn-group.mr-1
          = link_to 'Show', b, class: "btn btn-success btn-sm"
        .btn-group.mr-1
          - if policy(book).update?
            = link_to 'Edit', edit_book_path(b), class: "btn btn-warning btn-sm"
        .btn-group.mr-1
          - if policy(book).destroy?
            = link_to 'Destroy', b, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger btn-sm"

app/views/books/_form.html.slim
= form_for book, class: "form-group" do |f|
  - if book.errors.any?
    #error_explanation
      h2 = "#{pluralize(book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - book.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :book_image
    = f.file_field :book_image
    br
  .field
    = f.text_field :title, class: "form-control", placeholder: "Title"
    br
  .field
    = f.text_area :review, class: "form-control", placeholder: "Review", size: "25x15", required: true
    br
  .actions = f.submit

app/views/books/_review_comments.html.slim
- book.review_comments.each do |review_comment|
  h2
    = pluralize(review_comment.errors.count, "error")
    |  prohibited this review_comment from being saved:
  ul
    - review_comment.errors.full_messages.each do |message|
      li
        = message
  p
    = review_comment.body
  p
    = review_comment.user.email
  - if policy(review_comment).update?
    => link_to 'Edit', edit_book_review_comment_path(book, review_comment), class: "btn btn-warning btn-sm"
    '|
  - if policy(review_comment).destroy?
    =< link_to 'Destroy', [review_comment.book, review_comment], data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger btn-sm"
  hr

app/views/books/edit.html.slim
.col-md-4.offset-md-4
  h1 Editing book

  == render 'form'

  => link_to 'Show', book
  '|
  =< link_to 'Back', books_path

app/views/books/index.html.slim
.container
  .row
    .col-md-4.offset-md-5
      .books
        == render "books"
        br
        br
        br
        br
        br
        hr
      .col-md-4.offset-md-6
        = link_to 'New Book', new_book_path, class: "btn btn-success btn-lg btn-sm"

app/views/books/new.html.slim
.col-md-4.offset-md-4
  h1 New book

  == render 'form'

  = link_to 'Back', books_path, class: "btn btn-outline-primary btn-lg"

app/views/books/show.html.slim
p
.book
  .col-md-4.offset-md-4
    = image_tag book.book_image.url(:thumb)
  .col-md-4.offset-md-4
    table.table
      tr.book-title
        td
          | Title:
        td
          = book.title
      tr.book-review
        td
          | Review:
        td
          = book.review
      tr.overrall-rating
        td
          | Overrall rating:
        td
          - if book.rating.nil?
            | &nbsp No rating yet
          - else
            = book.rating
      tr.stars
        td
          | Stars:
        td
          - if book_rating
            = book_rating.rating_value
            => link_to 'Edit', edit_book_book_rating_path(book, book_rating)
          - else
            = render "book_rating"
      tr
        td
          | Author
        td
          = book.user.email

  .btn-group-justified.offset-md-5
    - if policy(book).update?
      => link_to 'Edit', edit_book_path(book), class: "btn btn-success btn-sm"
    - if policy(book).update?
      => link_to 'Destroy', book_path(book), method: :delete, class: "btn btn-warning btn-sm"
    =< link_to 'Back', books_path, class: "btn btn-danger btn-sm"

br
br
.comment
  .col-md-4.offset-md-4

    = form_with(model: [ book, ReviewComment.new ], local: true, class: "form-group") do |form|
      .field
        = form.label :body
        = form.text_field :body,  class: "form-control"

      = form.submit
    h2
      | Comments:
    = render 'review_comments'

app/views/layouts/_navigation.html.slim
.navbar-rigth
  ul.nav.navbar-nav.ml-auto.nav-link
    li.nav-item
      - if user_signed_in?
        = link_to 'Books', books_path
        = link_to 'Profile', root_path
        = link_to "Log out", destroy_user_session_path, :method => :delete
      - else
        = link_to "Log in", new_session_path(resource_name)
        = link_to "Sign up", new_registration_path(resource_name)

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Review'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Review'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags

  body
    p#notice = notice
    header
      = render 'layouts/navigation'
    = yield

app/views/review_comments/_form.html.slim
= form_for [:book, review_comment], class: "form-group" do |f|
  - if review_comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(review_comment.errors.count, "error")} prohibited this review_comment from being saved:"
      ul
        - review_comment.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :body
    = f.text_field :body, class: "form-control"
  .actions = f.submit

app/views/review_comments/edit.html.slim
.col-md-4.offset-md-4
  h1 Editing review_comment

  == render 'form'

  => link_to 'Show', [:book, review_comment]
  '|
  =< link_to 'Back', book_path(review_comment.book)

app/views/review_comments/index.html.slim
h1 Listing review_comments

table
  thead
    tr
      th Title
      th Body
      th Book
      th
      th
      th

  tbody
    - @review_comments.each do |review_comment|
      tr
        td = review_comment.body
        td = review_comment.book
        td = link_to 'Show', review_comment
        td = link_to 'Edit', edit_review_comment_path(review_comment)
        td = link_to 'Destroy', [review_comment.book, review_comment], data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Review comment', new_review_comment_path

app/views/review_comments/new.html.slim
h1 New review_comment

== render 'form'

= link_to 'Back', review_comments_path

app/views/review_comments/show.html.slim
p
  strong Body:
  = review_comment.body
p
  strong Book:
  = review_comment.book

=> link_to 'Edit', edit_review_comment_path(review_comment)
'|
=< link_to "Back", review_comment.book

app/views/users/_form.html.slim
= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
  .field
  = f.label :email
  br
  = f.email_field :email, autofocus: true, autocomplete: "email"
  .field
  = f.label :password
  br
  = f.password_field :password, autocomplete: "off"
  - if devise_mapping.rememberable?
  .field
    = f.check_box :remember_me
    = f.label :remember_me
  .actions
  = f.submit "Log in"
  = render "devise/shared/links"

app/views/users/profile.html.slim
.col-md-4.offset-md-5

  .round-image-50
    = image_tag current_user.avatar.url(:thumb)
  .row
    - if user_signed_in?
      .col-md-6
        | Hello,
        = current_user.email
    - else
      = render 'form'
.col-md-4.offset-md-5.my-margin-top
  .btn-group
    .btn.btn-outline-success = link_to 'Edit profile info', edit_user_registration_path
    / .btn.btn-outline-primary = link_to 'Мои заметки', my_events_path